package ExtendedLego.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_7399713840549617337(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xb486f0c9730c4d3cL, 0xb173e48b03fdb9c5L, 0x66b1108859800177L, 0x66b1108859808c28L, "variable")), MetaAdapterFactory.getProperty(0xb486f0c9730c4d3cL, 0xb173e48b03fdb9c5L, 0x66b11088597cab66L, 0x66b11088597cabb1L, "value"));
  }
}
