package ExtendedLegoSolution.Foo;

/*Generated by MPS */

import javax.swing.JFrame;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;
import java.awt.Dimension;

public class Foo extends JFrame {
  public static class Robot {
    private int x;
    private int y;

    public enum Orientation {
      NORTH(),
      EAST(),
      SOUTH(),
      WEST()
    }

    private Foo.Robot.Orientation orientation;
    private Color color;

    public Robot(int x, int y, Foo.Robot.Orientation orientation, Color color) {
      this.x = x;
      this.y = y;
      this.orientation = orientation;
      this.color = color;
    }

    public void Fwd(Graphics graphics, int units) {
      int x1 = this.x;
      int y1 = this.y;

      switch (this.orientation) {
        case NORTH:
          y1 -= units;
          break;
        case SOUTH:
          y1 += units;
          break;
        case WEST:
          x1 -= units;
          break;
        case EAST:
          x1 += units;
          break;
      }

      graphics.setColor(this.color);
      graphics.drawLine(this.x, this.y, x1, y1);
      this.x = x1;
      this.y = y1;
    }

    public void Left() {
      switch (this.orientation) {
        case SOUTH:
          this.orientation = Foo.Robot.Orientation.EAST;
          break;
        case EAST:
          this.orientation = Foo.Robot.Orientation.NORTH;
          break;
        case NORTH:
          this.orientation = Foo.Robot.Orientation.WEST;
          break;
        case WEST:
          this.orientation = Foo.Robot.Orientation.SOUTH;
          break;
      }
    }

    public void Right() {
      switch (this.orientation) {
        case SOUTH:
          this.orientation = Foo.Robot.Orientation.WEST;
          break;
        case EAST:
          this.orientation = Foo.Robot.Orientation.SOUTH;
          break;
        case NORTH:
          this.orientation = Foo.Robot.Orientation.EAST;
          break;
        case WEST:
          this.orientation = Foo.Robot.Orientation.NORTH;
          break;
      }
    }

  }


  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      Foo.Robot robot = new Foo.Robot(0, 0, Foo.Robot.Orientation.EAST, Color.BLACK);
      graphics.drawRect(0, 0, 500, 500);
      int a = 200;
      int b = 150;
      robot.Fwd(graphics, 100);
      robot.Right();
      robot.Fwd(graphics, 100 + 100);
      robot.Left();
      robot.Fwd(graphics, a + b);
      robot.Left();
      robot.Fwd(graphics, 100 + a);
    }
  };

  public void initialize() {
    this.setTitle("Foo");
    this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }

  public static void main(String[] args) {
    Foo route = new Foo();
    route.initialize();
  }
}
