package Lego2.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Dimension;

public class MyRoute extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      System.out.println("Boundary");
      System.out.println("Fwd");
      System.out.println("Left");
    }
  };

  private int posX = 0;
  private int posY = 0;
  private int direction = 0;

  public void initialize() {
    this.setTitle("Foo");
    this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }
  public static void main(String[] args) {
    MyRoute route = new MyRoute();
    route.initialize();
  }

}
