package ExtendedLego.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.concept.SConceptAdapterById;
import jetbrains.mps.smodel.adapter.structure.concept.SInterfaceConceptAdapterById;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.SNodePointer;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  private final Map<SConceptId, Integer> myIndexMap = new HashMap<SConceptId, Integer>(4);
  /*package*/ final ConceptDescriptor myConceptExtendedRoute = createDescriptorForExtendedRoute();
  /*package*/ final ConceptDescriptor myConceptFwd1 = createDescriptorForFwd1();
  /*package*/ final ConceptDescriptor myConceptFwd2 = createDescriptorForFwd2();
  /*package*/ final ConceptDescriptor myConceptVariable = createDescriptorForVariable();

  public StructureAspectDescriptor() {
    myIndexMap.put(myConceptExtendedRoute.getId(), 0);
    myIndexMap.put(myConceptFwd1.getId(), 1);
    myIndexMap.put(myConceptFwd2.getId(), 2);
    myIndexMap.put(myConceptVariable.getId(), 3);
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptExtendedRoute, myConceptFwd1, myConceptFwd2, myConceptVariable);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    Integer index = myIndexMap.get(id);
    if (index == null) {
      return null;
    }
    switch (((int) index)) {
      case 0:
        return myConceptExtendedRoute;
      case 1:
        return myConceptFwd1;
      case 2:
        return myConceptFwd2;
      case 3:
        return myConceptVariable;
      default:
        throw new IllegalStateException();
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    Integer res = null;
    if (c instanceof SConceptAdapterById) {
      res = myIndexMap.get(((SConceptAdapterById) c).getId());
    } else if (c instanceof SInterfaceConceptAdapterById) {
      res = myIndexMap.get(((SInterfaceConceptAdapterById) c).getId());
    }
    return (res == null ? -1 : res);
  }

  private static ConceptDescriptor createDescriptorForExtendedRoute() {
    return new ConceptDescriptorBuilder("ExtendedLego.structure.ExtendedRoute", MetaIdFactory.conceptId(0xb486f0c9730c4d3cL, 0xb173e48b03fdb9c5L, 0x66b11088597cabb8L)).super_("Lego2.structure.Route").version(1).super_(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223bad65L)).parents("Lego2.structure.Route", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223bad65L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x66b11088597caf32L, "variables", MetaIdFactory.conceptId(0xb486f0c9730c4d3cL, 0xb173e48b03fdb9c5L, 0x66b11088597cab66L), true, true, false, new SNodePointer("r:9bee8459-ffa8-439d-b8d3-20a68ba85ece(ExtendedLego.structure)", "7399713840549375794"))).children(new String[]{"variables"}, new boolean[]{true}).rootable().sourceNode(new SNodePointer("r:9bee8459-ffa8-439d-b8d3-20a68ba85ece(ExtendedLego.structure)", "7399713840549374904")).create();
  }
  private static ConceptDescriptor createDescriptorForFwd1() {
    return new ConceptDescriptorBuilder("ExtendedLego.structure.Fwd1", MetaIdFactory.conceptId(0xb486f0c9730c4d3cL, 0xb173e48b03fdb9c5L, 0x66b1108859800177L)).super_("Lego2.structure.Fwd").version(1).super_(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badeaL)).parents("Lego2.structure.Fwd").parentIds(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badeaL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(0x66b1108859808c28L, "variable", MetaIdFactory.conceptId(0xb486f0c9730c4d3cL, 0xb173e48b03fdb9c5L, 0x66b11088597cab66L), false, new SNodePointer("r:9bee8459-ffa8-439d-b8d3-20a68ba85ece(ExtendedLego.structure)", "7399713840549628968"))).references("variable").alias("Fwd1", "").sourceNode(new SNodePointer("r:9bee8459-ffa8-439d-b8d3-20a68ba85ece(ExtendedLego.structure)", "7399713840549593463")).create();
  }
  private static ConceptDescriptor createDescriptorForFwd2() {
    return new ConceptDescriptorBuilder("ExtendedLego.structure.Fwd2", MetaIdFactory.conceptId(0xb486f0c9730c4d3cL, 0xb173e48b03fdb9c5L, 0x50e739214d6a75eaL)).super_("Lego2.structure.Fwd").version(1).super_(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badeaL)).parents("Lego2.structure.Fwd").parentIds(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badeaL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x50e739214d6a7608L, "exp", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL), true, false, false, new SNodePointer("r:9bee8459-ffa8-439d-b8d3-20a68ba85ece(ExtendedLego.structure)", "5829691057849923080"))).children(new String[]{"exp"}, new boolean[]{false}).alias("Fwd2", "").sourceNode(new SNodePointer("r:9bee8459-ffa8-439d-b8d3-20a68ba85ece(ExtendedLego.structure)", "5829691057849923050")).create();
  }
  private static ConceptDescriptor createDescriptorForVariable() {
    return new ConceptDescriptorBuilder("ExtendedLego.structure.Variable", MetaIdFactory.conceptId(0xb486f0c9730c4d3cL, 0xb173e48b03fdb9c5L, 0x66b11088597cab66L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x66b11088597cabb1L, "value", new SNodePointer("r:9bee8459-ffa8-439d-b8d3-20a68ba85ece(ExtendedLego.structure)", "7399713840549374897"))).properties("value").alias("Variable", "").sourceNode(new SNodePointer("r:9bee8459-ffa8-439d-b8d3-20a68ba85ece(ExtendedLego.structure)", "7399713840549374822")).create();
  }
}
