package Lego2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.concept.SConceptAdapterById;
import jetbrains.mps.smodel.adapter.structure.concept.SInterfaceConceptAdapterById;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.SNodePointer;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  private final Map<SConceptId, Integer> myIndexMap = new HashMap<SConceptId, Integer>(8);
  /*package*/ final ConceptDescriptor myConceptBoundary = createDescriptorForBoundary();
  /*package*/ final ConceptDescriptor myConceptCommand = createDescriptorForCommand();
  /*package*/ final ConceptDescriptor myConceptForward = createDescriptorForForward();
  /*package*/ final ConceptDescriptor myConceptLeft = createDescriptorForLeft();
  /*package*/ final ConceptDescriptor myConceptRight = createDescriptorForRight();
  /*package*/ final ConceptDescriptor myConceptRoute = createDescriptorForRoute();
  /*package*/ final ConceptDescriptor myConceptStart = createDescriptorForStart();
  /*package*/ final ConceptDescriptor myConceptStatement = createDescriptorForStatement();

  public StructureAspectDescriptor() {
    myIndexMap.put(myConceptBoundary.getId(), 0);
    myIndexMap.put(myConceptCommand.getId(), 1);
    myIndexMap.put(myConceptForward.getId(), 2);
    myIndexMap.put(myConceptLeft.getId(), 3);
    myIndexMap.put(myConceptRight.getId(), 4);
    myIndexMap.put(myConceptRoute.getId(), 5);
    myIndexMap.put(myConceptStart.getId(), 6);
    myIndexMap.put(myConceptStatement.getId(), 7);
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBoundary, myConceptCommand, myConceptForward, myConceptLeft, myConceptRight, myConceptRoute, myConceptStart, myConceptStatement);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    Integer index = myIndexMap.get(id);
    if (index == null) {
      return null;
    }
    switch (((int) index)) {
      case 0:
        return myConceptBoundary;
      case 1:
        return myConceptCommand;
      case 2:
        return myConceptForward;
      case 3:
        return myConceptLeft;
      case 4:
        return myConceptRight;
      case 5:
        return myConceptRoute;
      case 6:
        return myConceptStart;
      case 7:
        return myConceptStatement;
      default:
        throw new IllegalStateException();
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    Integer res = null;
    if (c instanceof SConceptAdapterById) {
      res = myIndexMap.get(((SConceptAdapterById) c).getId());
    } else if (c instanceof SInterfaceConceptAdapterById) {
      res = myIndexMap.get(((SInterfaceConceptAdapterById) c).getId());
    }
    return (res == null ? -1 : res);
  }

  private static ConceptDescriptor createDescriptorForBoundary() {
    return new ConceptDescriptorBuilder("Lego2.structure.Boundary", MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x54ae31ec3ac549a9L)).super_("Lego2.structure.Statement").version(1).super_(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x409bb44bf973e751L)).parents("Lego2.structure.Statement").parentIds(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x409bb44bf973e751L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x66b11088597a3876L, "posx", new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "7399713840549214326")), new ConceptDescriptorBuilder.Prop(0x66b11088597a387aL, "posy", new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "7399713840549214330")), new ConceptDescriptorBuilder.Prop(0x54ae31ec3ac549c5L, "length", new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "6101869435801651653")), new ConceptDescriptorBuilder.Prop(0x54ae31ec3ac549c7L, "width", new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "6101869435801651655"))).properties("posx", "posy", "length", "width").alias("Boundary", "").sourceNode(new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "6101869435801651625")).create();
  }
  private static ConceptDescriptor createDescriptorForCommand() {
    return new ConceptDescriptorBuilder("Lego2.structure.Command", MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badceL)).super_("Lego2.structure.Statement").version(1).super_(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x409bb44bf973e751L)).parents("Lego2.structure.Statement").parentIds(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x409bb44bf973e751L)).sourceNode(new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "1901822991100784078")).create();
  }
  private static ConceptDescriptor createDescriptorForForward() {
    return new ConceptDescriptorBuilder("Lego2.structure.Forward", MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badeaL)).super_("Lego2.structure.Command").version(1).super_(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badceL)).parents("Lego2.structure.Command").parentIds(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badceL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x1a64a1ef223bae09L, "distance", new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "1901822991100784137"))).properties("distance").alias("Forward", "").sourceNode(new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "1901822991100784106")).create();
  }
  private static ConceptDescriptor createDescriptorForLeft() {
    return new ConceptDescriptorBuilder("Lego2.structure.Left", MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223df524L)).super_("Lego2.structure.Command").version(1).super_(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badceL)).parents("Lego2.structure.Command").parentIds(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badceL)).alias("Left", "").sourceNode(new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "1901822991100933412")).create();
  }
  private static ConceptDescriptor createDescriptorForRight() {
    return new ConceptDescriptorBuilder("Lego2.structure.Right", MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223bae2fL)).super_("Lego2.structure.Command").version(1).super_(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badceL)).parents("Lego2.structure.Command").parentIds(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223badceL)).alias("Right", "").sourceNode(new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "1901822991100784175")).create();
  }
  private static ConceptDescriptor createDescriptorForRoute() {
    return new ConceptDescriptorBuilder("Lego2.structure.Route", MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x1a64a1ef223bad65L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.execution.util.structure.IMainClass").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x409bb44bf973e76dL, "Statements", MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x409bb44bf973e751L), true, true, false, new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "4655512878218209133"))).children(new String[]{"Statements"}, new boolean[]{true}).rootable().alias("Route", "").sourceNode(new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "1901822991100783973")).create();
  }
  private static ConceptDescriptor createDescriptorForStart() {
    return new ConceptDescriptorBuilder("Lego2.structure.Start", MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x409bb44bf97a6031L)).super_("Lego2.structure.Statement").version(1).super_(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x409bb44bf973e751L)).parents("Lego2.structure.Statement").parentIds(MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x409bb44bf973e751L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x409bb44bf97a610aL, "startx", new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "4655512878218633482")), new ConceptDescriptorBuilder.Prop(0x409bb44bf97a610eL, "starty", new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "4655512878218633486"))).properties("startx", "starty").sourceNode(new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "4655512878218633265")).create();
  }
  private static ConceptDescriptor createDescriptorForStatement() {
    return new ConceptDescriptorBuilder("Lego2.structure.Statement", MetaIdFactory.conceptId(0x36d35b3e5a784042L, 0x8b0ed6682dd36f87L, 0x409bb44bf973e751L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).sourceNode(new SNodePointer("r:0bab23f2-7522-4039-b58b-542c2e2539f8(Lego2.structure)", "4655512878218209105")).create();
  }
}
